# Generated by Django 5.1.1 on 2025-10-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
